### ISSUE TITLE
Wrong way to calculate Literacy rate 

### ISSUE THREAD

**Issue by Satyampd** [nishusharma1608/India-Census-2011-Analysis#1]

**Comment by Satyampd** [comment]
According to census of 2001, a person aged 7 years and above who can read and write with understanding in any language is treated as literate.

For example, in your notebook Punjab literacty rate is 67.42929419668246, but in real it is  75.84.

**Comment by nishusharma1608** [comment]
I have mentioned that already in the notebook. Please read through it and
get back in case of any queries.
